# Generated by Django 4.0.3 on 2022-03-15 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='favourite',
            new_name='favorite',
        ),
    ]
